"""Prompt loader — parses a markdown prompt file into chat messages.

You do NOT edit this file. Edit the markdown prompt (default: prompts/default.md).
The harness calls load_prompt(path) once, then build_prompt(spec, sample, shots).

The markdown has four `## ` sections: System, Actions, Examples, Question.
See prompts/default.md for the format.
"""
import re
from dataclasses import dataclass

from src.data import ALL_CLASSES, serialize

LABELS = ALL_CLASSES


@dataclass
class PromptSpec:
    system: str
    actions: dict          # name -> definition (kept in file order)
    examples: list         # list of (session_text, action)
    question: str          # contains "{context}" placeholder


def _split_sections(text):
    """Return {section_title_lower: body} for each '## Title' block."""
    parts = re.split(r"(?m)^##\s+(.+?)\s*$", text)
    # parts = [preamble, title1, body1, title2, body2, ...]
    out = {}
    for i in range(1, len(parts), 2):
        out[parts[i].strip().lower()] = parts[i + 1].strip()
    return out


def _parse_actions(body):
    actions = {}
    for line in body.splitlines():
        m = re.match(r"^\s*-\s*([a-z_]+)\s*:\s*(.+?)\s*$", line)
        if m:
            actions[m.group(1)] = m.group(2)
    return actions


def _parse_examples(body):
    """Blocks separated by a line containing only '---'. Last line = 'NEXT ACTION: x'."""
    examples = []
    for block in re.split(r"(?m)^\s*-{3,}\s*$", body):
        block = block.strip()
        if not block:
            continue
        m = re.search(r"(?mi)^NEXT ACTION:\s*([a-z_]+)\s*$", block)
        if not m:
            continue
        action = m.group(1)
        ctx = block[: m.start()].strip()
        examples.append((ctx, action))
    return examples


def load_prompt(path):
    """Parse a markdown prompt file into a PromptSpec, validating the action set."""
    with open(path, encoding="utf-8") as f:
        text = f.read()
    sec = _split_sections(text)
    for req in ("system", "actions", "examples", "question"):
        if req not in sec:
            raise ValueError(f"prompt file missing '## {req.title()}' section: {path}")

    actions = _parse_actions(sec["actions"])
    missing = set(ALL_CLASSES) - set(actions)
    extra = set(actions) - set(ALL_CLASSES)
    if missing or extra:
        raise ValueError(f"Actions must be exactly the 14 classes. missing={missing} extra={extra}")
    if "{context}" not in sec["question"]:
        raise ValueError("'## Question' section must contain the {context} placeholder")

    return PromptSpec(
        system=sec["system"].strip(),
        actions=actions,
        examples=_parse_examples(sec["examples"]),
        question=sec["question"],
    )


def _allowed_block(spec):
    lines = [f"- {name}: {desc}" for name, desc in spec.actions.items()]
    return "Allowed actions:\n" + "\n".join(lines)


def build_prompt(spec, sample, shots=2, max_hist=6):
    """spec: PromptSpec from load_prompt(). sample: raw JSON dict.

    Returns chat messages [{role, content}, ...]. The answer is NOT included —
    the harness appends each candidate label when scoring.
    """
    ctx = serialize(sample, max_hist=max_hist)
    blocks = [_allowed_block(spec)]

    if shots > 0 and spec.examples:
        ex = ["Here are some examples:"]
        for ex_ctx, ex_ans in spec.examples[:shots]:
            ex.append(f"\nSESSION:\n{ex_ctx}\nNEXT ACTION: {ex_ans}")
        blocks.append("\n".join(ex))

    blocks.append(spec.question.replace("{context}", ctx))

    return [
        {"role": "system", "content": spec.system},
        {"role": "user", "content": "\n\n".join(blocks)},
    ]
